### ISSUE TITLE
Alliance Bug

### ISSUE THREAD

**Issue by sirgawain0x** [HausDAO/haus-tasks#15]
**Expected Behavior**
DAO should be cloned to xDAI

**Actual Behavior**
A message: 
Summon a DAO

Check your wallet for a transaction to confirm

**Application area**

    daohaus.club: https://app.daohaus.club/dao/0x89/0xc48996a569911fd6eba1b97b6419731eed32041e/uberhaus/clone

**More Details**

Add any relevant context to help the developer quickly to identify the issue

Step to reproduce:
Clone a DAO through Alliance menu button

   Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/1490181/127555856-3c68370a-bfda-43d8-b2f2-d0100a5724fe.png)

Idea(s) for possible solution

**Comment by arentweall** [comment]
Hi @gawainb, thanks for raising this! However, I just wanted to confirm that the issue you're facing is that there's no wallet transaction to confirm after summoning your DAO

**Comment by sirgawain0x** [comment]
> Hi @gawainb, thanks for raising this! However, I just wanted to confirm that the issue you're facing is that there's no wallet transaction to confirm after summoning your DAO
> 

Hi @amosgoh yes that's correct. So as a result the cloning of the DAO to xDai does not execute.

**Comment by arentweall** [comment]
Got it, and thanks again for raising this!  We are looking into it and will get back if we've updates! 

If you're interested in helping us fix bugs, do join us on our [#open-chat channel](https://discord.gg/XVSTJuyE) on Discord :)
