### ISSUE TITLE
Fix bug: Execute minion button showing on funding proposal to a minion address 

### ISSUE THREAD

**Issue by arentweall** [HausDAO/haus-tasks#16]
This is a bug fix 

### Expected Behavior
WHEN a funding proposal is passed 
AND the user wants to send funds to a Minion address 
THEN the proposal card  / details should show "Funding Proposal" 
THEN the proposal action should NOT show an "Execute Minion" button 

### Actual Behavior
WHEN a funding proposal is passed 
AND the user wants to send funds to a Minion address 
**THEN the proposal card  / details shows "Minion Proposal" 
THEN the proposal action shows an "Execute Minion" button** 

### Application area
* **Repository**: https://github.com/HausDAO/daohaus-app
*  **Proposals page's Execute Minion button** (after minion proposal is passed) 
(Error example [here](https://app.daohaus.club/dao/0x2a/0x3d3da6c64ba0b12505e6826c6c1eda78f4c2a34a/proposals/3))
* **Steps to reproduce**: 
1:  Create a funding proposal to transfer funds to a Minion address
2: Pass & process the proposal 
3: See the "Minion Proposal" title and "Execute Minion" button 

### What help is needed? 
  * Change title from "Minion Proposal" to "Funding Proposal" if proposal is a funding proposal (to a minion address)
  * Check getAction call. DO NOT display "Execute Minion button" if response is 
`[ 0, 
0x0000000000000000000000000000000000000000,
  0x0000000000000000000000000000000000000000,
  false,
  '0x',
  0x0000000000000000000000000000000000000000,
  0
]`

**Comment by skuhlmann** [comment]
this has been fixed.
