### ISSUE TITLE
Improve copy on membership & non-membership proposals ("applicant" vs "recipient") 

### ISSUE THREAD

**Issue by arentweall** [HausDAO/haus-tasks#20]
## Spec Type
* **Feature**: UX Improvement
* **Spec Size**: Single Task

## Overview
Currently, for all proposals, when a DAO member wants to enter their address for receiving funds, the membership form modal shows "Add Applicant". This works for membership proposals but for other proposals (e.g. funding), it should be changed from "Applicant" to "Recipient".
### **Problem**:
WHEN a new DAO applicant submits a membership proposal 
AND clicks "Additional Options" 
THEN the modal shows "Applicant" as list of dropdown 

WHEN a new DAO applicant clicks "Applicant" 
THEN the membership form modal shows a field 
AND then field is labelled "Applicant" 

For non-membership proposals, the use of "Applicant" is misleading in the above 2 scenarios

### **Solution**:
**IF proposal is a Membership Proposal, show "applicant" in the above 2 fields** 
WHEN the proposal submitted is a Membership Proposal
AND clicks "Additional Options" 
_THEN the modal should display "Membership Proposal" instead of "New Member Proposal"_ 
AND the modal should  show "Applicant" as list of dropdown 

WHEN a DAO member clicks "Applicant" 
THEN the membership form modal shows a field 
AND then field is labelled "Applicant" 

**IF proposal is not a Membership Proposal, show "recipient" in the above 2 fields** 
WHEN the proposal submitted is NOT a Membership Proposal
AND clicks "Additional Options" 
_THEN the modal should show  "Recipient" as list of dropdown_ 

WHEN the proposal submitted is NOT a Membership Proposal 
AND an existing DAO member clicks "Recipient" 
THEN the membership form modal shows a field 
_AND then field is labelled  "Recipient"_ 

### **Implementation Details:**
* Are there wireframes or code patterns? No
* Does this require any third-party integrations? No
* Repos: https://github.com/HausDAO/daohaus-app/
* Documentation: -
* Test Resources: - 
* Deliverable
  *  For Membership Proposals: Change proposal type from "New Member Proposal" to "Membership Proposal" 
  * For non-Membership Proposals: Change "Applicant" copy to "Recipient in the 2 screens above 
Notes

**Comment by skuhlmann** [comment]
this has been fixed
